"""conversations, messages, and provider/billing tables

Revision ID: 0001_conversations_messages_providers
Revises:
Create Date: 2026-07-21

Hand-written (not autogenerated) since there is no live database in this
environment to diff against. Creates the chat-history schema proposed in
progress.md's decisions log, adapted from Dify's Conversation/Message models
(see progress.md for the specific departures: org_id-scoped RLS, one row per
turn, per-message model attribution, real FTS/pgvector columns).

org_id/user_id columns are plain UUID with no FK constraint — the
organizations/users tables land with Phase 1 E1. Add those FKs in a follow-up
migration once E1 exists; the RLS policies below already assume org_id is
populated correctly by the application layer in the meantime.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001_conversations_messages_providers"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

EMBEDDING_DIM = 1536


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table(
        "conversations",
        sa.Column(
            "id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("org_id", sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("title", sa.String(255)),
        sa.Column("default_model_provider", sa.String(64)),
        sa.Column("default_model_id", sa.String(128)),
        sa.Column("status", sa.String(16), nullable=False, server_default="active"),
        sa.Column("is_pinned", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("is_deleted", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("deleted_at", sa.DateTime(timezone=True)),
        sa.Column("search_tsv", sa.dialects.postgresql.TSVECTOR),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
    )
    op.create_index("ix_conversations_org_updated", "conversations", ["org_id", "updated_at"])
    op.create_index(
        "ix_conversations_search_tsv", "conversations", ["search_tsv"], postgresql_using="gin"
    )

    op.create_table(
        "messages",
        sa.Column(
            "id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("org_id", sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "conversation_id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            sa.ForeignKey("conversations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "parent_message_id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            sa.ForeignKey("messages.id", ondelete="SET NULL"),
        ),
        sa.Column("role", sa.String(16), nullable=False),
        sa.Column("content", sa.Text, nullable=False),
        sa.Column("model_provider", sa.String(64)),
        sa.Column("model_id", sa.String(128)),
        sa.Column("prompt_tokens", sa.Integer, nullable=False, server_default="0"),
        sa.Column("completion_tokens", sa.Integer, nullable=False, server_default="0"),
        sa.Column("total_tokens", sa.Integer, nullable=False, server_default="0"),
        sa.Column("estimated_cost_usd", sa.Numeric(12, 6), nullable=False, server_default="0"),
        sa.Column("latency_ms", sa.Integer),
        sa.Column("status", sa.String(16), nullable=False, server_default="normal"),
        sa.Column("error", sa.Text),
        sa.Column(
            "content_tsv",
            sa.dialects.postgresql.TSVECTOR,
            sa.Computed("to_tsvector('english', content)", persisted=True),
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
    )
    # pgvector's Vector type isn't a stock sqlalchemy.dialects.postgresql
    # type, so it's added via raw SQL rather than op.create_table's column
    # list above (op.create_table can't reference the pgvector dialect type
    # without importing pgvector.sqlalchemy at the top of this file).
    op.execute(f"ALTER TABLE messages ADD COLUMN embedding vector({EMBEDDING_DIM})")

    op.create_index(
        "ix_messages_org_conversation_created",
        "messages",
        ["org_id", "conversation_id", "created_at"],
    )
    op.create_index("ix_messages_content_tsv", "messages", ["content_tsv"], postgresql_using="gin")
    op.execute(
        "CREATE INDEX ix_messages_embedding_hnsw ON messages "
        "USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)"
    )

    op.create_table(
        "provider_credentials",
        sa.Column(
            "id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("org_id", sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("provider", sa.String(64), nullable=False),
        sa.Column("encrypted_config", sa.String, nullable=False),
        sa.Column("is_default", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
    )
    op.create_index(
        "ix_provider_credentials_org_provider", "provider_credentials", ["org_id", "provider"]
    )

    op.create_table(
        "model_profile_overrides",
        sa.Column(
            "id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("org_id", sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("profile_name", sa.String(64), nullable=False),
        sa.Column("litellm_model", sa.String(255)),
        sa.Column("api_base", sa.String(255)),
        sa.Column(
            "default_params", sa.dialects.postgresql.JSONB, nullable=False, server_default="{}"
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
    )
    op.create_index(
        "ix_model_profile_overrides_org_profile",
        "model_profile_overrides",
        ["org_id", "profile_name"],
    )

    op.create_table(
        "inference_usage_logs",
        sa.Column(
            "id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("org_id", sa.dialects.postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", sa.dialects.postgresql.UUID(as_uuid=True)),
        sa.Column("request_id", sa.String(64), nullable=False),
        sa.Column("model_profile", sa.String(64), nullable=False),
        sa.Column("litellm_model", sa.String(255), nullable=False),
        sa.Column("prompt_tokens", sa.Integer, nullable=False, server_default="0"),
        sa.Column("completion_tokens", sa.Integer, nullable=False, server_default="0"),
        sa.Column("total_tokens", sa.Integer, nullable=False, server_default="0"),
        sa.Column("cost_usd", sa.Numeric(12, 6), nullable=False, server_default="0"),
        sa.Column("latency_ms", sa.Integer),
        sa.Column("status", sa.String(16), nullable=False, server_default="ok"),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()
        ),
    )
    op.create_index(
        "ix_inference_usage_logs_org_created", "inference_usage_logs", ["org_id", "created_at"]
    )

    # Conversation.search_tsv aggregates its messages' content, so it can't
    # be a per-row generated column — kept in sync with a trigger instead.
    op.execute("""
        CREATE OR REPLACE FUNCTION afridock_refresh_conversation_search_tsv()
        RETURNS trigger AS $$
        BEGIN
          UPDATE conversations
          SET search_tsv = (
            SELECT to_tsvector('english', string_agg(content, ' '))
            FROM messages
            WHERE conversation_id = NEW.conversation_id
          )
          WHERE id = NEW.conversation_id;
          RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """)
    op.execute("""
        CREATE TRIGGER messages_refresh_conversation_search_tsv
        AFTER INSERT OR UPDATE OF content ON messages
        FOR EACH ROW
        EXECUTE FUNCTION afridock_refresh_conversation_search_tsv();
        """)

    # Multi-tenant isolation (plan principle: hard isolation at the data
    # layer). `true` as current_setting's second arg returns NULL instead of
    # raising when app.org_id hasn't been set for the session — during local
    # dev/migrations that means "no rows visible" rather than an error.
    for table in (
        "conversations",
        "messages",
        "provider_credentials",
        "model_profile_overrides",
        "inference_usage_logs",
    ):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"""
            CREATE POLICY {table}_tenant_isolation ON {table}
            USING (org_id = current_setting('app.org_id', true)::uuid)
            """)


def downgrade() -> None:
    for table in (
        "inference_usage_logs",
        "model_profile_overrides",
        "provider_credentials",
        "messages",
        "conversations",
    ):
        op.execute(f"DROP POLICY IF EXISTS {table}_tenant_isolation ON {table}")

    op.execute("DROP TRIGGER IF EXISTS messages_refresh_conversation_search_tsv ON messages")
    op.execute("DROP FUNCTION IF EXISTS afridock_refresh_conversation_search_tsv()")

    op.drop_table("inference_usage_logs")
    op.drop_table("model_profile_overrides")
    op.drop_table("provider_credentials")
    op.drop_table("messages")
    op.drop_table("conversations")
